config/routes.rb
MutualLikes::Application.routes.draw do

  root 'home#login'
  get '/friends' => 'home#friends', as: :friends
  get '/likes/:id' => 'home#likes', as: :likes

  match '/oauth/callback' => 'oauth#callback', as: :callback, via: [:get], trailing_slash: true
  get '/oauth/failure' => 'home#failure', as: :failure
  get '/oauth/logout' => 'oauth#logout', as: :logout

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper
  before_filter :check_token, only: [:friends, :likes]

  def login
    @auth_url = Koala::Facebook::OAuth.new.url_for_oauth_code(callback: callback_url, permissions: 'user_likes,user_friends,friends_likes')
  end

  def friends
    @friends = @graph.get_connections("me", "friends")
    @friends.sort_by! { |f| f['name'] }
  end

  def likes
    @friend = @graph.get_object(params[:id])
    #
    # Fetch all likes, since they are paged
    user_likes = @graph.get_connections("me", "likes", limit: 1000)
    while (next_likes = user_likes.next_page)
      user_likes += next_likes
    end
    #
    # Fetch friend likes
    friend_likes = @graph.get_connections(@friend['id'], "likes", limit: 1000)
    while (next_likes = friend_likes.next_page)
      friend_likes += next_likes
    end
    #
    # Get intersection of likes
    @intersect_likes = likes_intersect(user_likes, friend_likes)
  end

  def failure
  end

  private

  def check_token
    if session[:access_token]
      @graph = Koala::Facebook::API.new(session[:access_token])
    else
      redirect_to root_path
    end
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def callback
    if params[:error] == 'access_denied'
      flash[:error] = "Access denied."
      redirect_to failure_path
    end

    session[:access_token] = Koala::Facebook::OAuth.new(callback_url).get_access_token(params[:code]) if params[:code]

    if session[:access_token]
      redirect_to friends_path
    else
      flash[:error] = "Invalid auth code :%s." % params[:code]
      redirect_to failure_path
    end
  end

  def logout
    session[:access_token] = nil
    render text: "You've been logged out."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def likes_intersect(likes1, likes2)
    likes2_id_set = likes2.map { |e| e['id'] }.to_set
    likes1.select {|e| likes2_id_set.include? e['id'] }
  end
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/views/home/friends.html.erb
<h2>Select a friend to view mutual likes</h2>

<% @friends.each do |friend| %>
  <%= link_to(friend['name'], likes_path(id: friend['id'])) %>
  <br>
<% end %>

app/views/home/likes.html.erb
<h2>Mutual likes with <%= @friend['name'] %></h2>

<% if @intersect_likes.empty? %>

  <i>No shared likes</i>

<% else %>

  <ul>
    <% @intersect_likes.each do |like| %>
      <li><%= like['name'] %></li>
    <% end %>
  </ul>

<% end %>

<br>

<%= link_to "Back to friends", friends_path %>

app/views/home/login.html.erb
<%= link_to "Sign in with Facebook", @auth_url, class: "zocial facebook" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MutualLikes" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "MutualLikes", friends_path, class: "brand" %>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Logout", logout_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>